### PR TITLE
Place upper bound in cryptography indirect dependency

### LINKED ISSUE #424: [15.0] external dependency "cryptography" causes error 'X509_V_FLAG_CB_ISSUER_CHECK'
## Module auth_jwt
The name of the module that has a bug.
auth_jwt has an external dependency "cryptography" which seems not be compatible with Odoo anymore:
https://github.com/odoo/odoo/commit/55d2da4dd28975e78ace2a6beeae4168d5692f09

## Describe the bug
The Odoo server is not starting because of dependency incompatibilities. 
similar topics:
https://github.com/odoo/odoo/pull/89798
https://www.odoo.com/de_DE/forum/hilfe-1/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check-when-creating-new-staging-branch-202955

## To Reproduce
**Affected versions**: 15.0
Odoo does not start when this repository is added to the addon folder.
Error: 
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

1. I am using Odoo.sh with an empty database referencing this repository. The server with an empty db does not start.

**Expected behavior**

**Additional context**
I've added the following line to the requirements.txt and the error is gone:
cryptography==36.0.2 # last version working with pyopenssl==19.0.0

But I am not using the auth_jwt module, so I am not sure if the module is still working with the changed requirements.txt?
Is this something this repository should react on, or will this probably be fixed in odoo?

### PR DESCRIPTION
**Pull request by sbidoul**
Fixes #424

### CODE REVIEW

**Comment by sbidoul** [comment]
runboat is green @CRogos

**Comment by CRogos** [comment]
Have you tested that pysaml2 is working with cryptography < 3.1?
Otherwise it would be best to limit pysaml2 to version < 7.2 and not limit cryptography.

https://github.com/IdentityPython/pysaml2/compare/v7.1.2...v7.2.0

**Comment by sbidoul** [comment]
> Otherwise it would be best to limit pysaml2 to version < 7.2 and not limit cryptography.

Why? In this case installing `pysaml2 cryptography<37` yields cryptography 36, so this should be fine?
I'm not using auth_saml though so I can't tell for sure.

**Comment by CRogos** [comment]
Because with the update of pysaml2 7.1.2 -> 7.2.0 the dependency was changed:
image

There might be a reason?

**Review by CRogos — APPROVED** [review]
I confirm that the change fixes the build issue.

**Comment by sbidoul** [comment]
> Have you tested that pysaml2 is working with cryptography < 3.1?
> Otherwise it would be best to limit pysaml2 to version < 7.2 and not limit cryptography.

In any case this should be a question for auth_saml users and maintainers.

/ocabot merge patch

**Comment by CRogos** [comment]
@sbidoul I agree. Thank you, for your support. I've learned a lot.
